name: swiftui-ui-text-input-paste-image-demo
options:
  bundleIdPrefix: com.freewind.demos
settings:
  base:
    SWIFT_VERSION: 6.0
targets:
  swiftui_ui_text_input_paste_image_demo:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_NAME: swiftui-ui-text-input-paste-image-demo
        PRODUCT_BUNDLE_IDENTIFIER: com.freewind.demos.swiftui-ui-text-input-paste-image-demo
        GENERATE_INFOPLIST_FILE: YES
